CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL
);
CREATE INDEX "ix_users_email" ON "users" ("email");

CREATE TABLE "accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "bank_name" varchar(100),
  "balance" numeric(12,2) NOT NULL,
  "currency" varchar(10) NOT NULL DEFAULT 'EUR'
);

CREATE TABLE "user_account_access" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "account_id" int NOT NULL,
  "role" varchar(50) NOT NULL DEFAULT 'owner',
  UNIQUE (user_id, account_id)
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar(100) NOT NULL,
  "type" varchar(50) NOT NULL
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int NOT NULL,
  "category_id" int,
  "name" varchar(50) NOT NULL,
  "amount" numeric(12,2),
  "date" date NOT NULL,
  "description" text NOT NULL,
  "currency" varchar(10) NOT NULL,
  "source" varchar(20) NOT NULL,
  "external_id" varchar(100)
);

CREATE TABLE "psd2_connection" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "account_id" int UNIQUE,
  "bank_name" varchar(100) NOT NULL,
  "client_id" varchar(255),
  "access_token" TEXT,
  "refresh_token" TEXT,
  "token_expires_at" timestamp,
  "last_synced" timestamp
);

CREATE TABLE "account_invitations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int NOT NULL,
  "invited_by_user_id" int NOT NULL,
  "invited_email" varchar(255) NOT NULL,
  "role" varchar(50) NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'pending',
  "created_at" timestamp,
  "expires_at" timestamp NOT NULL
);


ALTER TABLE "user_account_access" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_account_access" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "psd2_connection" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "psd2_connection" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "account_invitations" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") ON DELETE CASCADE;

ALTER TABLE "account_invitations" ADD FOREIGN KEY ("invited_by_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
