CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL
);

CREATE TABLE "accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "bank_name" varchar(100),
  "balance" numeric(12,2),
  "currency" varchar(10) DEFAULT 'EUR'
);

-- Defines the roles a user can have on an account
CREATE TYPE account_role AS ENUM ('viewer', 'editor', 'manager', 'owner');

-- Defines the status of an account invitation
CREATE TYPE invitation_status AS ENUM ('pending', 'accepted', 'declined', 'expired');

CREATE TABLE "user_account_access" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "account_id" int NOT NULL,
  "role" account_role DEFAULT 'viewer' NOT NULL,
  UNIQUE (user_id, account_id)
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar(100) NOT NULL,
  "type" varchar(50) NOT NULL
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int NOT NULL,
  "category_id" int,
  "name" varchar(50) NOT NULL,
  "amount" numeric(12,2) NOT NULL,
  "date" date DEFAULT (now()),
  "description" text,
  "currency" varchar(10) DEFAULT 'EUR',
  "source" varchar(20) DEFAULT 'manual',
  "external_id" varchar(100)
);

CREATE TABLE "psd2_connection" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "account_id" int,
  "bank_name" varchar(100),
  "client_id" varchar(255),
  "access_token" varchar(255),
  "refresh_token" varchar(255),
  "token_expires_at" timestamp,
  "last_synced" timestamp DEFAULT (now())
);

CREATE TABLE "currency_rates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "target_currency" varchar(10),
  "rate" numeric(10,4),
  "date" date DEFAULT (now())
);

CREATE TABLE "account_invitations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int NOT NULL,
  "invited_by_user_id" int NOT NULL,
  "invited_email" varchar(255) NOT NULL,
  "role" account_role NOT NULL,
  "token" varchar(255) UNIQUE NOT NULL,
  "status" invitation_status DEFAULT 'pending' NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "expires_at" timestamp NOT NULL
);


ALTER TABLE "user_account_access" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_account_access" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "psd2_connection" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "psd2_connection" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "account_invitations" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") ON DELETE CASCADE;

ALTER TABLE "account_invitations" ADD FOREIGN KEY ("invited_by_user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
